# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev',
                'doc_host': 'https://gxu932335.github.io',
                'git_url': 'https://github.com/gxu932335/nbdev',
                'lib_path': 'nbdev'},
  'syms': {'nbdev.core': {'nbdev.core.foo': ('core.html#foo', 'nbdev/core.py')}}}